# Generated by Django 5.2.9 on 2025-12-22 14:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RankKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(max_length=500, verbose_name="کلمه کلیدی"),
                ),
                (
                    "current_rank",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="رتبه فعلی"
                    ),
                ),
                (
                    "previous_rank",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="رتبه قبلی"
                    ),
                ),
                (
                    "highest_rank",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="بهترین رتبه"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "کلمه کلیدی",
                "verbose_name_plural": "کلمات کلیدی",
                "db_table": "rank_tracker_keywords",
                "ordering": ["keyword"],
            },
        ),
        migrations.CreateModel(
            name="RankHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(blank=True, null=True, verbose_name="رتبه"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ بررسی"),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="rank_tracker.rankkeyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه رتبه",
                "verbose_name_plural": "تاریخچه رتبه\u200cها",
                "db_table": "rank_tracker_history",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="RankProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="نام پروژه"),
                ),
                (
                    "target_domain",
                    models.CharField(max_length=255, verbose_name="دامنه هدف"),
                ),
                (
                    "keyword_capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="ظرفیت کلمات کلیدی",
                    ),
                ),
                (
                    "update_count_current_month",
                    models.IntegerField(default=0, verbose_name="تعداد آپدیت این ماه"),
                ),
                (
                    "last_update_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین آپدیت"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه ردیابی رتبه",
                "verbose_name_plural": "پروژه\u200cهای ردیابی رتبه",
                "db_table": "rank_tracker_projects",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="rankkeyword",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="rank_tracker.rankproject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rankkeyword",
            unique_together={("project", "keyword")},
        ),
    ]
