# Generated by Django 5.2.9 on 2025-12-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rank_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankhistory",
            name="ranked_page_title",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="عنوان صفحه"
            ),
        ),
        migrations.AddField(
            model_name="rankhistory",
            name="ranked_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="URL صفحه"
            ),
        ),
        migrations.AddField(
            model_name="rankkeyword",
            name="ranked_page_title",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="عنوان صفحه"
            ),
        ),
        migrations.AddField(
            model_name="rankkeyword",
            name="ranked_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="URL صفحه"
            ),
        ),
    ]
