# Generated by Django 5.2.7 on 2025-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0004_keyword_akw_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='status',
            field=models.IntegerField(choices=[(0, 'مقایسه نشده'), (1, 'PKW (Primary Keyword)'), (2, 'AKW (Auxiliary Keyword)')], default=0),
        ),
    ]
