# Generated by Django 4.2.7 on 2025-09-15 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(default='fas fa-cog', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='رنگ')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی ماژول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای ماژول',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(max_length=255, verbose_name='توضیحات کوتاه')),
                ('module_type', models.CharField(choices=[('wordpress_plugin', 'افزونه وردپرس'), ('online_tool', 'ابزار آنلاین'), ('api_service', 'سرویس API')], max_length=20, verbose_name='نوع ماژول')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='نسخه')),
                ('min_wp_version', models.CharField(blank=True, max_length=10, verbose_name='حداقل نسخه وردپرس')),
                ('pricing_type', models.CharField(choices=[('one_time', 'پرداخت یکباره'), ('monthly', 'اشتراک ماهانه'), ('credit_based', 'بر اساس اعتبار'), ('free', 'رایگان')], max_length=15, verbose_name='نوع قیمت\u200cگذاری')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت ماهانه')),
                ('credit_cost', models.IntegerField(blank=True, null=True, verbose_name='هزینه اعتبار')),
                ('features', models.TextField(help_text='هر ویژگی در یک خط', verbose_name='ویژگی\u200cها')),
                ('requirements', models.TextField(blank=True, verbose_name='پیش\u200cنیازها')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('maintenance', 'در حال تعمیر'), ('coming_soon', 'به زودی'), ('deprecated', 'منسوخ شده')], default='active', max_length=15, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('icon', models.ImageField(blank=True, upload_to='module_icons/', verbose_name='آیکون')),
                ('banner', models.ImageField(blank=True, upload_to='module_banners/', verbose_name='بنر')),
                ('demo_url', models.URLField(blank=True, verbose_name='لینک دمو')),
                ('download_count', models.IntegerField(default=0, verbose_name='تعداد دانلود')),
                ('purchase_count', models.IntegerField(default=0, verbose_name='تعداد خرید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.modulecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ماژول',
                'verbose_name_plural': 'ماژول\u200cها',
                'ordering': ['-is_featured', '-is_popular', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('price_paid', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('license_key', models.CharField(max_length=64, unique=True, verbose_name='کلید مجوز')),
                ('allowed_domains', models.TextField(blank=True, help_text='هر دامنه در یک خط', verbose_name='دامنه\u200cهای مجاز')),
                ('max_domains', models.IntegerField(default=1, verbose_name='حداکثر دامنه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module', verbose_name='ماژول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ماژول کاربر',
                'verbose_name_plural': 'ماژول\u200cهای کاربران',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
