# Generated by Django 5.2.7 on 2025-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.IntegerField()),
                ('links', models.TextField(blank=True)),
                ('word_count', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
