# Generated by Django 5.1.2 on 2025-12-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0002_keyword_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
