# Generated by Django 5.1.2 on 2025-12-09 21:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0003_alter_keyword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 9, 21, 21, 51, 760243, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='original_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='keyword_research.researchrequest'),
        ),
    ]
