# Generated by Django 5.2.7 on 2025-10-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0003_researchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='akw_str',
            field=models.TextField(blank=True),
        ),
    ]
