# Generated by Django 5.1.2 on 2025-12-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0004_keyword_created_date_keyword_original_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='intent_mapping',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='meta_titles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='researchrequest',
            name='ai_analysis_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
